### ISSUE TITLE
variant_02/Front_Panel.stl doesn't 'fit' with associated case

### ISSUE THREAD

**Issue by tandell** [Settorezero/Supplino#1]
Hello,

I was getting ready to print the variant_02 case when I noticed that the Front_Panel.stl doesn't fit in the associated case. 

![image](https://user-images.githubusercontent.com/6440979/172019349-bb4bdcfa-791e-491c-bec1-62a24c5e3b79.png)

Not sure if it's my slicer (Cura 5.0.0 & Cura 4.6.1), or if it got accidentally stretched during export, or something else. 

This isn't blocking me or anything, I'm _probably_ going to make my own (vertical-style) case. Just thought you might want to know.

Awesome project and excellent writeup, by the way!

Ref link: https://github.com/Settorezero/Supplino/blob/main/cad/stl/variant_02/FrontPanel.stl

**Comment by MrLoba81** [comment]
Hi @tandell thank you for the interest and for the issue, I have just updated the front panel STL file. Sorry for the problem. Enjoy the project ☺️
